management:
  endpoint:
    health.enabled: true
    camelroutes:
      enabled: true
      read-only: true
  endpoints.web.exposure.include: info,health,camelroutes

camel:
  springboot.name: av-overview-sync

application:
  batch-ingest: 
    enabled: true
    type: EMBEDDED
  file:
    directory: "target/batch"
    file-name: "company-overview.json"
    watch: false
    watch-period: 30000
    update: false
  s3:
    access-key: "<access-key>"
    secret-key: "<secret-key>"
    bucket-name: "default"
    region-name: "us-east-1"
    file-name: "company-overview.json"
    watch: false
    watch-period: 30000
    update: false
  poller:
    enabled: true
    symbols:
      - "IBM"
    period: 86400000
  alpha-vantage:
    scheme: "https"
    host: "www.alphavantage.co"
    port: 443
    path: "query"
    function: "OVERVIEW"
    api-key: "demo"
    throttle-enabled: true
    throttle-requests: 1
    throttle-period: 1000
  weaviate:
    scheme: "http"
    host: "localhost"
    port: 8000
    grpc-secured: false
    grpc-host: "localhost"
    grpc-port: 50051
    api-key: "<api-key>"
    headers:
      "X-OpenAI-Api-key": "<openai-api-key>"
      "X-Huggingface-Api-key": "<huggingface-api-key>"
    initialize-schema: true
    schema:
      initialize: true
      drop-if-exists: false
      name: "Symbols"
#      vectorizer: "text2vec-ollama"
#      module-config:
#        text2vec-ollama: 
#          apiEndpoint: "http://localhost:11434"
#          model: "all-minilm"
#        generative-ollama: 
#          apiEndpoint: "http://localhost:11434"
#          model: "llama3"
    throttle-enabled: true
    throttle-requests: 1
    throttle-period: 1000
