management:
  endpoint:
    health.enabled: true
    camelroutes:
      enabled: true
      read-only: true
  endpoints.web.exposure.include: info,health,camelroutes

camel:
  springboot.name: av-overview-sync

application:
  batch-ingest: 
    enabled: true
    type: EMBEDDED
  file:
    directory: "target/batch"
    file-name: "company-overview.json"
    watch: false
    watch-period: 30000
    update: false
  s3:
    access-key: "<access-key>"
    secret-key: "<secret-key>"
    bucket-name: "default"
    region-name: "us-east-1"
    file-name: "company-overview.json"
    watch: false
    watch-period: 30000
    update: false
  poller:
    enabled: true
    symbols:
      - "IBM"
    period: 86400000
  alpha-vantage:
    scheme: "https"
    host: "www.alphavantage.co"
    port: 443
    path: "query"
    function: "OVERVIEW"
    api-key: "demo"
    throttle-enabled: true
    throttle-requests: 1
    throttle-period: 1000
  weaviate:
    scheme: "http"
    host: "localhost"
    port: 8000
    grpc-secured: false
    grpc-host: "localhost"
    grpc-port: 50051
    api-key: "<api-key>"
    headers: {}
    initialize-schema: true
    schema:
      initialize: true
      drop-if-exists: false
      name: "Symbols"
      properties:
        - name: "twohundredDayMovingAverage"
          data-types:
            - "text"
        - name: "fiftyDayMovingAverage"
          data-types:
            - "text"
        - name: "fiftytwoWeekLow"
          data-types:
            - "text"
        - name: "fiftytwoWeekHigh"
          data-types:
            - "text"
        - name: "Address"
          data-types:
            - "text"
        - name: "analystRatingBuy"
          data-types:
            - "text"
        - name: "analystRatingHold"
          data-types:
            - "text"
        - name: "analystRatingSell"
          data-types:
            - "text"
        - name: "analystRatingStrongBuy"
          data-types:
            - "text"
        - name: "analystRatingStrongSell"
          data-types:
            - "text"
        - name: "analystTargetPrice"
          data-types:
            - "text"
        - name: "assetType"
          data-types:
            - "text"
        - name: "beta"
          data-types:
            - "text"
        - name: "bookValue"
          data-types:
            - "text"
        - name: "cIK"
          data-types:
            - "text"
        - name: "country"
          data-types:
            - "text"
        - name: "currency"
          data-types:
            - "text"
        - name: "description"
          data-types:
            - "text"
        - name: "dilutedEPSTTM"
          data-types:
            - "text"
        - name: "dividendDate"
          data-types:
            - "text"
        - name: "dividendPerShare"
          data-types:
            - "text"
        - name: "dividendYield"
          data-types:
            - "text"
        - name: "eBITDA"
          data-types:
            - "text"
        - name: "ePS"
          data-types:
            - "text"
        - name: "eVToEBITDA"
          data-types:
            - "text"
        - name: "eVToRevenue"
          data-types:
            - "text"
        - name: "exDividendDate"
          data-types:
            - "text"
        - name: "exchange"
          data-types:
            - "text"
        - name: "fiscalYearEnd"
          data-types:
            - "text"
        - name: "forwardPE"
          data-types:
            - "text"
        - name: "grossProfitTTM"
          data-types:
            - "text"
        - name: "industry"
          data-types:
            - "text"
        - name: "latestQuarter"
          data-types:
            - "text"
        - name: "marketCapitalization"
          data-types:
            - "text"
        - name: "name"
          data-types:
            - "text"
        - name: "operatingMarginTTM"
          data-types:
            - "text"
        - name: "pEGRatio"
          data-types:
            - "text"
        - name: "pERatio"
          data-types:
            - "text"
        - name: "priceToBookRatio"
          data-types:
            - "text"
        - name: "priceToSalesRatioTTM"
          data-types:
            - "text"
        - name: "profitMargin"
          data-types:
            - "text"
        - name: "quarterlyEarningsGrowthYOY"
          data-types:
            - "text"
        - name: "quarterlyRevenueGrowthYOY"
          data-types:
            - "text"
        - name: "returnOnAssetsTTM"
          data-types:
            - "text"
        - name: "returnOnEquityTTM"
          data-types:
            - "text"
        - name: "revenuePerShareTTM"
          data-types:
            - "text"
        - name: "revenueTTM"
          data-types:
            - "text"
        - name: "sector"
          data-types:
            - "text"
        - name: "sharesOutstanding"
          data-types:
            - "text"
        - name: "symbol"
          data-types:
            - "text"
        - name: "trailingPE"
          data-types:
            - "text"
      vectorizer-module: "text2vec-ollama"
      vectorizer-module-config:
        apiEndpoint: "http://localhost:11434"
        model: "all-minilm"
      generative-module: "generative-ollama"
      generative-module-config:
        apiEndpoint: "http://localhost:11434"
        model: "llama3"
    throttle-enabled: true
    throttle-requests: 1
    throttle-period: 1000
